language: python
sudo: false
python:
      - "3.6"
install:
    - "pip install -r requirements-test.txt"
    - "pip install coveralls pytest-cov"
script:
    - "EAS_SETTINGS='eas/settings/tests.py' python -m pytest tests --cov=eas"
after_success:
    - coveralls
