language: python
sudo: false
python:
      - "3.6"
install:
    - "pip install -r requirements-test.txt"
    - "pip install coveralls pytest-cov"
script:
    - make test
    - make lint
after_success:
    - coveralls
